debug_mode = false

[world]
seed = 12345
width = 10000
height = 10000
# generation_rules would likely be a nested table matching your struct

[network]
default_port = 7878
max_players = 64
connection_timeout_ms = 5000

[terrain]
max_threads = 7 # Example: Default based on detection or a sensible value
chunk_size = 32
blend_distance = 75.0
use_parallel_processing = true
chunk_cache_size = 600
chunks_per_frame = 4
render_distance = 4 # Moved from terrain_initializer
amplification = 4.0
mesh_updates_per_frame = 4
blend_noise_strength = 0.25 # NEW: Controls intensity of noise for blending (0.0 to ~0.5 is a good range)

[terrain.noise_paths]
"1" = "res://project/terrain/noise/corralNoise.tres"
"2" = "res://project/terrain/noise/sandNoise.tres"
"3" = "res://project/terrain/noise/rockNoise.tres"
"4" = "res://project/terrain/noise/kelpNoise.tres"
"5" = "res://project/terrain/noise/lavaRockNoise.tres"
"blend" = "res://project/terrain/noise/blendNoise.tres"
"biome_blend" = "res://project/terrain/noise/blendNoise.tres"
"section" = "res://project/terrain/noise/sectionNoise.tres"
"section_biome_blend" = "res://project/terrain/noise/section_blending/biome_blend_section.tres"

# [custom_settings] # If needed
# my_custom_value = "example"

# Section definitions
[[sections]]
id = 1
length = 200.0
transition_zone = 50.0
possible_biomes = [1, 2]


[[sections]]
id = 2
length = 200.0
transition_zone = 50.0
possible_biomes = [3, 4]

[[sections]]
id = 3
length = 200.0
transition_zone = 50.0
possible_biomes = [4, 5]

# Biome definitions
[[biomes]]
id = 1
name = "Coral"
primary_noise_key = "1"
texture_params = { roughness = 0.7, metallic = 0.1 }

[[biomes]]
id = 2
name = "Sand"
primary_noise_key = "2"
texture_params = { roughness = 0.9, metallic = 0.0 }

[[biomes]]
id = 3
name = "Rock"
primary_noise_key = "3"
texture_params = { roughness = 0.6, metallic = 0.2 }

[[biomes]]
id = 4
name = "Kelp"
primary_noise_key = "4"
texture_params = { roughness = 0.5, metallic = 0.1 }
secondary_noise_keys = ["kelp_detail_noise"]

[[biomes]]
id = 5
name = "Volcanic"
primary_noise_key = "5"
texture_params = { roughness = 0.6, metallic = 0.3 }
secondary_noise_keys = ["heat_noise"]