debug_mode = false

[world]
seed = 12345
width = 10000
height = 10000
# generation_rules would likely be a nested table matching your struct

[network]
default_port = 7878
max_players = 64
connection_timeout_ms = 5000

[terrain]
max_threads = 7 # Example: Default based on detection or a sensible value
chunk_size = 32
blend_distance = 400.0
use_parallel_processing = true
chunk_cache_size = 600
chunks_per_frame = 4
render_distance = 2 # Moved from terrain_initializer

[terrain.noise_paths]
"1" = "res://project/terrain/noise/corralNoise.tres"
"2" = "res://project/terrain/noise/sandNoise.tres"
"3" = "res://project/terrain/noise/rockNoise.tres"
"4" = "res://project/terrain/noise/kelpNoise.tres"
"5" = "res://project/terrain/noise/lavaRockNoise.tres"
"blend" = "res://project/terrain/noise/blendNoise.tres"
"biome_blend" = "res://project/terrain/noise/blendNoise.tres"
"section" = "res://project/terrain/noise/sectionNoise.tres"

# [custom_settings] # If needed
# my_custom_value = "example"